### ISSUE TITLE
Unreadable text in index plot

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#110]
I think that the mtext call should be placing the index on side = 2, see the resulting figure below.
https://github.com/iantaylor-NOAA/Lingcod_2021/blob/654ac8b2c413071d886fe9e01885e325442cc0a4/R/plot_indices.R#L85

![image](https://user-images.githubusercontent.com/4108564/123535708-63c4f980-d6da-11eb-881f-7bc4ee63bf9a.png)

**Comment by kellijohnson-NOAA** [comment]
While, I am on the topic of this figure, it is in the document twice, once as raw data and once again with fits. Was this intentional?

**Comment by iantaylor-NOAA** [comment]
Fixed in 5239bf2. Please remove the data-only plot. That was added back when we had data-only plots for lots of other things. There's also an unused log-scale plot that I'm happy to leave out but could be useful in the future. I'll leave this open until you remove the data plot as part of ongoing changes to 53figures.Rmd.
