### ISSUE TITLE
Model folders in github

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#128]
@iantaylor-NOAA I see a number of model runs in the README.md file that are not showing up in my models folder (e.g. 2021.n.021.002_more_asymptotic_manual) and Im all caught up with my pulls. Most are of sensitivities, so is there a trick to get all of the model folders that Im missing? No worries if these haven't been pushed. 

I also see a number of southern model runs in the README.md file that wouldn't be run (e.g. 2021.s.014.313_no_Rec_WA_index, which has a FALSE indicator in the sensitivites.csv). I have no problems with this as a consequence of our workflow. Are the models in the README but are not run only related to sensitivities?

**Comment by iantaylor-NOAA** [comment]
Sorry @brianlangseth-NOAA, I didn't push those files because got worried about bloating the repository with lots of large model files. I just uploaded the sensitivities for the current north and south base models to Google Drive here: https://drive.google.com/drive/folders/1hccvKPY9tbZcCJZeV5b5Ch2YNSK8vYqx.

The 'dontrun' column in sensitivities.csv never got implemented in `run_sensitivities()`--I just ran sets of numbers that didn't include those models. I just pushed my messy script from which I copy and pasted sections to run and make tables from the sensitivities: [models/model_sensitivity_output.R](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/model_sensitivity_output.R)

**Comment by brianlangseth-NOAA** [comment]
Thanks Ian

**Comment by brianlangseth-NOAA** [comment]
Ive been able to run some models but am not seeing these show up as changes in git Desktop (because of .gitignore). To push I can either edit the .gitignore file, push my models, and then revert my edits for .gitignore. An alternative, as @kellijohnson-NOAA says, is to use git add -f <file> using the command line. @kellijohnson-NOAA Because this needs to be done for many files within each model folder, do you have a script with all of the git add commands already there?

**Comment by kellijohnson-NOAA** [comment]
I have tried to think about the best way forward for this and I believe a makefile could be configured to work quite well here, but it would require use of the command line. We could also globally revert the gitignore file and users would then have to rely on `git status -uno` to hide the status of untracked files.

**Comment by kellijohnson-NOAA** [comment]
After some experimentation, I think we can do
```
git add -f models\foldername\*someregexexpression
```
where I am working on what that expression would be, so hold tight.

**Comment by iantaylor-NOAA** [comment]
Thanks for running the sensitivities. 

Two easy options that I've used recently are to locally modify .gitignore to add a line like 
`!/models/2021.n.022.302*`
which would allow you to commit the (not-otherwise-ignored) files from that particular model.

Or to just put the models in that sensitivities folder on Google Drive (which could be re-organized): https://drive.google.com/drive/folders/1hccvKPY9tbZcCJZeV5b5Ch2YNSK8vYqx

**Comment by brianlangseth-NOAA** [comment]
Along with above commit, I also added syntex to be able to push R scripts in the model folders (ce3746906027be0e631497cdeb6eb0f3f360e106).

After pushing these I found out that I also needed to add a * after models/ 

# additions on June 23 to help Ian navigate git better
/models/*

in order for my changes to show up. This final change does not need to be committed or pushed for Git Desktop so I did not in case the syntax changes does not work for @iantaylor-NOAA
