### ISSUE TITLE
Day 1 STAR panel request 1

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#137]
1. Explore freeing up the width parameter on sex specific selectivity curves, including offsets, for trawl North, trawl South, and fixed gear South. Do not have this parameter time varying. This exploration will be for North and South. Provide likelihood profiles for M on the age and length data. The range of M are to be for female 0.18 to 0.58 in steps of 0.05.
2
Rationale: There is depth gradient by sex that would suggest sex specific selectivity. The request may help understand the tension between age and length composition data.

**Comment by iantaylor-NOAA** [comment]
Flat top was estimated to be be quite small in the north model and effectively zero in the south model (north left, south right in fig below):
![image](https://user-images.githubusercontent.com/4992918/125393728-51df8980-e35d-11eb-8888-d4d8fdf5aab2.png)
Time series of spawning biomass is indistinguishable from the sex-specific selectivity sensitivity (sens = 404) described in presentation 3.

We can discuss in the morning whether it makes more sense to run an _M_ profile on these new models or the original sensitivity. Either one would teach us something about the impact of the sex-specific selectivity on the signals about M from age and length data (at least for the north where more ages are present).

The two model ids are 2021.n.022.408 and 2021.s.014.407 because it was quickest to make them using `run_sensitivities()` We can renumber these with new model numbers if that helps run the profiles on them (should we choose to do so, instead of on those without the flat top. Input and output were added to the repo on 4c106f8164ccb1bbeb0df10af61270600164c1c6.
