### ISSUE TITLE
STAR panel Request 10

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#150]
### Request:

Perform runs for both North and South base models with the Lorenzen mortality
function. The reference age for the naturality mortality prior should be age eight (8).
Provide the model comparisons slides and tables/figures with likelihoods and key
parameter outputs, selectivity outputs, etc. for panel review.

### Rationale:

Allowing for a variable natural mortality with age for fish less than age 8 would be a more
realistic estimate of natural morality for smaller and immature fish. It is well documented that
natural mortality tends to be negatively correlated with body size.

**Comment by kellijohnson-NOAA** [comment]
South model has a the Triennial selectivity parameter on the bound -1. Any thoughts of how quickly we could get the younger age data into the model?
![image](https://user-images.githubusercontent.com/4108564/125682908-25247d94-1ae9-43a5-aa78-4305f658f488.png)

**Comment by iantaylor-NOAA** [comment]
The `ageCAAL_S_WCGBTS` and `ageCAAL_S_Triennial` available in the package is only sexed fish, so it would involve going back to the data processing.
@brianlangseth-NOAA would know better whether the existing tools could be used or if we should just run some bespoke code for binning the ages associated with small fish.

Alternative approaches to dealing with this parameter on bounds (presumably the descending slope) could be
- fix the parameter at -1 as was done for the one north model parameter (shifting to an even lower bound would not change the result much and create a less plausible drop-off in selectivity)
- add the sex-specific CAAL data for the triennial survey in case that helps
- fix one fleet to be asymptotic, previously we tested commercial fixed-gear, but it could be any fleet. 
 
The last option may pull up the descending limb of other selectivities, including triennial, because old fish would be estimated as dying faster rather than just less observed due to dome-shaped selectivity. There are competing schools of thought: one argues that we should expect dome-shaped selectivity in general for any fishery (see Sampson papers), the other is that if you don't make sure at least one selectivity is asymptotic then you risk having lots of cryptic biomass so it's good to pick at least one fleet to be asymptotic.

**Comment by kellijohnson-NOAA** [comment]
Size_DblN_ascend_se_6_Surv_TRI(6)

**Comment by iantaylor-NOAA** [comment]
That's a different story. In that case, I would either lower lower bound and/or free up parameter 5 which allows scaling of the initial selectivity.
That is, change the INIT from -999 to maybe 0 and PHASE from -2 to 2 in line 230:
 -5.00	  9	-999.0000	0	0	0	-2	0	0	0	0	0	0	0	#_SizeSel_P_5_6_Surv_TRI(6)

**Comment by kellijohnson-NOAA** [comment]
Okay, did both of those things, running now.

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA Here is the first pass on raw numbers of unsexed fish in the WCGBTS and Triennial surveys. Code would apply for survey_acomps.R. Top rows are ages, bottom and number at age. 

As you can see the matter is irrelevant for the Triennial survey (hardly any unsexed aged fish). Most unsexed fish with ages are age 0 in WCGBTS south. 

WCGBTS
> table(bioages_north[!is.na(bioages_north$Age) & bioages_north$Sex=="U",]$Age)
 0  1  2  3  4  5  6  7 
21 13  5  5  7  5  2  2 
> table(bioages_south[!is.na(bioages_south$Age) & bioages_south$Sex=="U",]$Age)
  0   1   2   3   5 
469  29   4   1   1 

Triennial
> table(bioages_north[!is.na(bioages_north$Age) & bioages_north$Sex=="U",]$Age)
0 3 4 
1 2 1 
> table(bioages_south[!is.na(bioages_south$Age) & bioages_south$Sex=="U",]$Age)
0 1 
2 7

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA Replying to your question above "Any thoughts of how quickly we could get the younger age data into the model?"

Unsexed fish are partitioned by gender (M or F) for marginal ages, and for lengths for triennial and WCGBTS. For CAAL, the nwfscSurvey package does not have capability to do CAAL for unsexed fish, and we made the call to exclude unsexed fish for CAAL early on. As you mentioned, a hack would be to assign all unsexed fish to female and rerun the CAAL, or to adjust create_caal_nonsurvey.R to include unsexed fish (though I haven't tried to see if that works yet).

**Comment by kellijohnson-NOAA** [comment]
Age-7 vs Age-8 was very different for South

![image](https://user-images.githubusercontent.com/4108564/125700953-c6cb1372-9e87-4b8f-9221-8fb80d172ed6.png)

**Comment by kellijohnson-NOAA** [comment]
Not different for the North
![image](https://user-images.githubusercontent.com/4108564/125701087-1247b7de-28b7-44fa-8eec-1bcfae4d3ea8.png)

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA I can revise create_caal_nonsurvey.R to produce CAAL for unsexed fish. I ran this for WCGBTS north and south as a test and it appears to be working.  Do you want these still? Given todays direction of discussion, I don't think its needed though, other than perhaps future functionality.

**Comment by kellijohnson-NOAA** [comment]
Thanks @brianlangseth-NOAA for looking into the values and @iantaylor-NOAA for the explanation on why they will not matter. I think this issue is done!
