### ISSUE TITLE
document - survey selectivity curves

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#184]
John Field noted that fishery selectivity curves were included but that the survey curves were not. I have not check to see if this is true, but nevertheless, we should get them in if they are not already there.

**Comment by iantaylor-NOAA** [comment]
Survey selectivity figures are appearing in both docs that I just compiled and it looks like they were present in earlier versions. However, they might be easy to miss because they are included in the same figure as rec selectivity and the caption is a bit terse.

![image](https://user-images.githubusercontent.com/4992918/139743935-8687da68-dc58-48ca-a5aa-d776b29800ec.png)
![image](https://user-images.githubusercontent.com/4992918/139743971-885daf54-05c8-4caa-8d66-ac0e56bb79e5.png)

**Comment by kellijohnson-NOAA** [comment]
Great. Thanks Ian!
