### ISSUE TITLE
lingcod package not loading

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#35]
When I try devtools::load_all() within my cloned directory Im now getting an error with the xlsx package. 

i Loading lingcod
Error: Dependency package(s) 'xlsx' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'xlsx' not available.

This is a bit surprising considering I thought the lingcod package was self contained. 

I tried installing xlsx but got another error. 

rror: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
In addition: Warning message:
package ‘xlsx’ was built under R version 4.0.5 

Anyone else having this issue? Any ideas for resolving?

**Comment by kellijohnson-NOAA** [comment]
Thanks for noting this @brianlangseth-NOAA I found the same thing on my NOAA computer this morning, and it has to do with how java is installed versus how java is typically installed, for some reason NOAA links it inside a program files folder. I haven't found a fix yet, so can you please move the package to suggests rather than imports in the Description file until I find a fix?

**Comment by brianlangseth-NOAA** [comment]
Thanks @kellijohnson-NOAA. This worked for me.
