### ISSUE TITLE
add line breaks to text files?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#42]
Breaking lines of text at 80 characters instead of having each paragraph on one line makes it easier to read .Rmd files on GitHub and see where changes in a paragraph are made as discussed for the Hake Assessment at https://github.com/pacific-hake/hake-assessment/issues/305.

Could we do that for Lingcod too? If so, one of us could start with the introduction that @andi-stephens-NOAA just added (#3).

As an emacs user, I can try the method that Andy Edwards proposed in that issue (pasted below). However, maybe there's another approach that is better.

> I'll do as separate branch 'linebreaks' which I can then merge. I'll highlight text and use
> `Alt-x-fill-region`
> in Emacs to force line breaks after 80 characters. Two things to be aware of:
> 
> 1. if searching a file for a phrase of text it may no longer show up because the phrase will get split over two lines (but may be sometimes split anyway) - but it is preferable to see changes more easily on GitHub.
> 2. Any comments [% .....] at the end of paragraphs may get uncommented if the %  happens to get put on the line before. I had this happen before and easily spotted it, but kind of think might not have any/many - sounds like the sort of thing Chris wouldn't allow ;)

**Comment by kellijohnson-NOAA** [comment]
I am having trouble with the doc\First_pass_Lingcod_Intro.Rmd file where it won't let me check it out because of the file line endings, it wants to recommit the entire file.
I would prefer to not arbitrarily break things at 80 characters using a script but rather do it based on sections that are likely to be edited, such as full stops, commas, and filler words.
I agree that 80 characters makes it easier to read on github b/c you don't have to scroll over. But, I also like the approach of having a full sentence / idea on a single line so it is more clear that you are editing a topic rather than arbitrary line numbers, and just using your editor to wrap lines. I am torn :(

**Comment by andi-stephens-NOAA** [comment]
In the olden days, line length was 78 characters, because of course
everything was printed on paper (even, or especially, code for review).

You might (?) notice that I coerced the Intro text into smaller paragraphs
for readability.   Giant blocks of text are too dense to work with.

**Comment by kellijohnson-NOAA** [comment]
I will / am parsing out the revamped introduction into multiple files and will truncate the lines to ~80 characters.
