### ISSUE TITLE
revisit/refine selectivity and discard assumptions

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#58]
Here are a few things we should think about for selectivity and retention. Please feel free to add or refine this list or post and questions, comments, or concerns.

- [x] Add selectivity for new DebWV fleet 10 (needs a new issue to track)
- [x] Start with the same initial assumption of which parameters are estimated for all fleets.  I'm happy to retain double-normal selectivity as the initial assumption and I like the setup used in many fleets for the previous assessments (listed below). However, some of these parameters got fixed in the final 2017 model (presumably for reasons documented in the report) which should be freed up.
   - [x] three estimated parameters 1 (peak), 2 (ascend), and 4 (descend), 
   - [x] parameter 3 (width of top) fixed at -15 to make a smooth transition from ascending to descending with no flat top, and 
   - [x] -999 used for parameters 5 and 6 to allow a smooth normal shape without additional scaling of initial and final values. 
- [x] revisit/refine blocking used for selectivity. We should check for additional management changes since 2016 which would have impacted selectivity. 
  - [x] add blocks for Rec_WA (#61)
  - [x] initially set Rec_CA in North model to have same block assumptions as Rec_CA is South?
  - [x] either provide more flexible discard changes for catch-shares era with precise discard estimates or increase uncertainty in the discard rates
  - [x] blocks for all the other fishing fleets
- [x] revisit the assumptions about retention for the early period before management restrictions led to an increase in discards
- [ ] revisit/refine assumptions about male offsets for selectivity
  - [ ] check which fleets fit significantly better with male offsets for selectivity
    > From 2017 report: "Sex specific size selectivities are estimated, where sex specific data allowed, using the double normal pattern (SS pattern 24) for all fleets and surveys. All surveys as well as the Oregon and California recreational data were modeled using combined male and female selectivity due to either combined sex data, or good fits to the data without sex specific selectivity curves."

**Comment by iantaylor-NOAA** [comment]
Description of status-quo blocking from page 57 of 2017 assessment report copied here (and reformatted) to save me looking it up each time.

In the **north** model selectivity and retention are estimated with time blocks such that: 
1. the fixed gear fleet uses blocks from 1998 to 2010 and 2011 to 2016 to account for management changes (e.g. gear changes and closed areas) and the implementation of the catch shares program, respectively, 
2. the trawl fleet uses blocks from 1998 to 2006, 2007 to 2009, 2010 to 2010, and 2011 to 2016 to account for management changes and the implementation of the catch shares program, and 
3. the Oregon recreational fleet uses blocks from 1999 to 2016 to account for management changes and observed changes in the composition data. 

In the **south** model selectivity and retention are estimated with time blocks such that: 
1. the fixed gear fleet uses blocks from 1998 to 2001, 2002 to 2002, 2003 to 2010, and 2011 to 2016 to account for management changes and the implementation of the catch shares program, 
2. the trawl fleet uses blocks from 1998 to 2006, 2007 to 2009, 2010 to 2010, and 2011 to 2016 to account for management changes and the implementation of the catch shares program, and 
3. the California recreational flees uses blocks from 1959 to 1974, 1975 to 1989, 1990 to 2003, and 2004 to 2016 to account data collection by different agencies and in different regions of the state. 

Not included in that description is a distinction between blocks on selectivity and retention for trawl and fixed-gear fleets.

**Comment by aliwhitman** [comment]
I'm chiming in with a question about the time block for the OR recreational fleet - 1999 as a start year for the block doesn't make a great deal of sense to me.  If this was motivated by the change from MRFSS to ORBS sampling programs, that should really start in 2001. In terms of management changes, in 1999, the lingcod bag limit was reduced from 3 to 2, and then it was further reduced from 2 to 1 in 2000, where it stayed until 2002.  Then it was bumped back up to 2 and has stayed there since. Size limits change a bit in that time period too, but again, it was multiple changes over a series of years (e.g. 1998 - 2001).  Anyway, a bit puzzling to me as to why that year might have been chosen.  Perhaps this was in combination with some management changes in WA?  

The commercial time blocks make sense to me.

**Comment by iantaylor-NOAA** [comment]
Thanks for the comment @aliwhitman. The patterns in the data support your view that a change in blocking for the OR recreational fleet is warranted.

The length composition from the OR recreational fleet as worked up by @brianlangseth-NOAA is shown in the plot below (black = unsexed, red = female, blue = male). The most obvious breaks appear to be 1995, 1998, and 2007. Are those years which had new size limits? I'm not sure how visible a change associated with a bag limit would be for these data.
![image](https://user-images.githubusercontent.com/4992918/121948484-26d92a00-cd0c-11eb-9427-851aea701152.png)

**Comment by aliwhitman** [comment]
1995 is the first year with a minimum size limit (of 22inches) so that one makes sense.  And in 1998, the 22 inch size limit was increased to 24.  In 2007, the min size limit was reduced from 24 to 22 inches. You can clearly see all of these, which is cool.  

What is also interesting is that we had a max size limit in place for one year only (2000) of 34 inches, and you can also see that as well.  

Based on these length comps and the management changes I detailed above, I might recommend considering 1995 as the best breakpoint.  I'm not sure how that would line up with WA's though.

**Comment by kellijohnson-NOAA** [comment]
2017 models underwent a lot of change during the STAR panel (e.g., recreational CPUE indices in the southern model). For each fleet, what are the reasonable break points.
What fleets need blocks, which parameters should be blocked (ascending limb) but if you shift the ascending limb the parameter will be tied together except maybe the ascending slope. For the both commercial fleets, the 2017 model had a mix of blocks with key retention parameters. For north model there was also a block on selectivity. Did management changes impact which fish were being selected or which fish were being kept?
- WA rec look for years in #61 
- OR rec fleet: max size limit in 2000; start with a separate block for each of the five periods and then remove blocks if there is trouble estimating those parameters; see years above; larger lingcod come in shore to breed so max size may not be depth dependent; 
- CA rec fleet: bigger changes are going to be south of point conception; 40-10 is not that much different (20-30 fathoms); minimum size limit in 1999? and reduced in 2011?; MM says worry about depth; 
- Can only estimate time-varying retention when we have data, which is since 2002. Before the late 1990s there was weak management and the Picketch? study found small discards in lingcod.

**Comment by iantaylor-NOAA** [comment]
It's taking me a long time to get the blocks revised, in part because I keep waffling about both where the block should go and whether to incrementally change the old settings or start fresh. I've finally decided that the best approach is to write a function to add the blocks and apply them to the right parameters in an automated way. This will give us additional flexibility to quickly switch between old and new approaches, refine the settings we choose, and explore the sensitivity to other options. I should be able to get that done this morning, and hopefully with the help of some better commercial comp data (#69), we can have a decent starting point for further model explorations.

**Comment by iantaylor-NOAA** [comment]
New process for adding blocking of selectivity and retention added in commit 39bd40e.
The workflow is now to 

1. modify [doc/selectivity.Rmd](https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/doc/selectivity.Rmd) to change which fleets have blocks on which parameters in which years
2. then run just the R code within it via
`knitr::purl("doc/selectivity.Rmd")`
`source("selectivity.R")`
`usethis::use_data(block_breaks, overwrite = TRUE)`
3. run `devtools::load_all()`
4. re-run the script models/lingcod_model_bridging_change_ctl.R

There are a few check marks open on the initial list and models are running now so need to confirm that the blocks are actually working as intended.

**Comment by iantaylor-NOAA** [comment]
Remaining tasks in this issue covered by new issue #118.
