### ISSUE TITLE
workflow for spell check?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#70]
As I write text for the reports in various documents which all get seamlessly knit together, I can see myself making spelling errors.

@kellijohnson-NOAA do you have a suggestion for the best way to spell check all this without getting tripped up by things that are not text for the document? Should we spell check the big .tex file which I presume gets created by pandoc on the way to the PDF and then trace the misspellings back to the individual files or what?

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA my solution for the data moderate was to spell check the individual .rmd files. I use Rstudio and that has a spell check option. Not sure if others do. Note that this really only worked because my .rmd files were primarily text documents (it wasn't too bad to move through R text). Of course, kelli probably has a more elegant way of doing it.

**Comment by kellijohnson-NOAA** [comment]
I think checking the final tex document within sublime or using hunspell is the best option because checking the Rmd files won't work for captions that are pasted together.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards how do you check the hake document?

**Comment by andrew-edwards** [comment]
I build the document, and then spellcheck the hake-assessment.tex file with aspell (or ispell) in Emacs, which ignores .tex commands. And then edit our .Rmd files. 

I'm not sure if there's a way to do the .Rmd files, but you'd have to open them all individually so that would take a while. I only do it twice - before submission and before the final version, so doesn't take long on the main hake-assessment.tex file.

**Comment by kellijohnson-NOAA** [comment]
Thanks @andrew-edwards I can do the same in sublime. I will leave emacs to you and @iantaylor-NOAA

**Comment by andrew-edwards** [comment]
Ha ha. Chris got me onto magit now, which is using git in emacs. Hands never need to leave the keyboard.

**Comment by kellijohnson-NOAA** [comment]
There you go Ian, one more thing to learn.

**Comment by kellijohnson-NOAA** [comment]
Did this roughly but it is a pain b/c of the number of LaTeX commands. Need to find a better way in the future.

**Comment by andrew-edwards** [comment]
Out of curiosity What did you use? (ispell/aspell in sublime, or something else?).

**Comment by kellijohnson-NOAA** [comment]
I just used view  - spell check in sublime.

**Comment by kellijohnson-NOAA** [comment]
Moved discussion to [sa4ss](github.com/nwfsc-assess/sa4ss).
