### ISSUE TITLE
writing items

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#75]
Issue that either need to be resolved as I am writing up the survye, biology, and rec sections. Will add as I go.  

- [x] Is there a publication for the Lam research data? Either in review, in press, or published would be fine.  
- [x] Need to confirm with Harms that description of hook and line survey is applicable for lingcod. (email sent 6/23)
- [x] Need to better scale Lam length frequency plots
- [x] Need to create Lam age plots
- [x] Need to provide write up for the NWFSC slope survey. Deafult text for AFSC slope survey is in sa4ss 
- [x] We have CAAL for many fleets. Its the default for Lam Research, Triennial, and WCGBTS. Is it also the default for the recreational fleets? Ive written it up as marginals as defaults for the recreational fleets, with CAAL as sensitivities, with the opposite for Triennial, WCGBTS, and the Hook and Line survey. 
- [x] Would appreciate a look over the historical CA fleets. My write up is VERY sparse. Either @melissamonk-NOAA or we can ask Budrick. Checking with MM on 6/23

**Comment by iantaylor-NOAA** [comment]
Lam, L. S. (2019). Geographic and habitat-based variation in lingcod (Ophiodon elongatus) demography and life-history along the U.S. west coast. Capstone Projects and Master’s Theses, 657. Retrieved from https://digitalcommons.csumb.edu/caps_thes_all/657

**Comment by iantaylor-NOAA** [comment]
Thanks for working on all this stuff, @brianlangseth-NOAA. 
- **H&L description**: this description seems accurate to my understanding. I don't recall any different treatment of lingcod from the rockfish in the H&L survey (other than collecting fin rays instead of otoliths).
- **NWFSC slope survey**: NWFSC and AFSC were indeed different but I'm happy to have the associated text really brief since neither source got used. See page 5 of the background doc ftp://ftp.pcouncil.org/pub/!2021%20GF%20STAR1_Dover&SpinyDogfish/Background%20materials/NWFSC_Fishery_Surveys_2021.pdf _[can't seem to make ftp links within github issue, but cut and paste works]_ for more info (recognizing that the same doc will be background for the Lingcod STAR and thus doesn't need to be repeated in any length).
- **CAAL vs marginal**: I didn't realize ageCAAL_N_OR_Rec and ageCAAL_N_WA_Rec were available. I'll explore a sensitivity to including those instead of the associated marginal ages in the N model. The benefit would be better a better match for the sampling design (#45), but if it causes the model to fit other sources less well, might not be worth the change. I'm happy to work on the write-up for this element.

**Comment by brianlangseth-NOAA** [comment]
Thank you @melissamonk-NOAA for comments. 910e1bc resolves

**Comment by iantaylor-NOAA** [comment]
nice working wrapping these up @brianlangseth-NOAA
