### ISSUE TITLE
STAR 2017 Unresolved Problem 1: include more age data

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#8]
Unresolved Problems and Major Uncertainties from 2017 STAR report bullet point 1:
> The models did not use the available age data sampled from the fishing fleets due to concerns that unsexed fish had been assigned equally to the sexes without regard to length and because of evidence there had been non-random subsampling of fish for age-reading.

The representation of more age data as conditioned on length and sex should avoid problems of non-random subsampling. Care still needs to be taken in treatment of unsexed fish where their treatment should depend on the sampling process that led to their remaining unsexed.

**Comment by kellijohnson-NOAA** [comment]
Note for KFJ for later, that if conditional age-at-length data are placed in SS using the same line for females and males, then the data will be used to inform sex ratios, where if they are placed on separate lines with placeholders for the opposite sex rather than data, then the data will not be used to inform sex ratios.

**Comment by iantaylor-NOAA** [comment]
Write up related to major uncertainties provided by @brianlangseth-NOAA. Lots of age data used in the north model, ages in the south showed problems and we chose to exclude them.
