### ISSUE TITLE
STAR 2017 Unresolved Problem 2: provide more information on consistency among ageing protocols

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#9]
Unresolved Problems and Major Uncertainties from 2017 STAR report bullet point 2:
> The available age-readings had been done by at least two laboratories. It was unclear that age-reading protocols had been employed consistently

This should not be hard to provide.

**Comment by kellijohnson-NOAA** [comment]
There are indeed double age-reads for lingcod, even triple reads for seven fish. Though it is unknown how the third age reader determined the age because PacFIN did not provide a AGE_METHOD_CODE for the second or third reads of these seven fish. If a method was recorded for the second age, it was break and burn. Though the AGENCY_AGE_STRUCTURE_CODE was always F or NA for second and third reads. First reads include F, L, O, SP, and NA.

We obviously cannot change how the age of fish were read, but it does need to be decided what we will do with break and burn versus fin reads.

**Comment by iantaylor-NOAA** [comment]
Note that @LaurelLam-NOAA cross reads from previous assessment are probably not in PacFIN. Follow up with Laurel on getting the data and updating the ageing imprecision estimation if needed.

**Comment by iantaylor-NOAA** [comment]
Write up related to major uncertainties provided by @brianlangseth-NOAA. Ageing uncertainty re-estimated. Not clear that between-lab ageing is an issue, although coming from California are harder to fit.
