### ISSUE TITLE
serve the r4ss plots on github to get permanent links

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#95]
r4ss/r4ss#414
@iantaylor-NOAA had a brilliant idea to do the following

- [x] 1. Go to "Pages" under github Settings https://github.com/iantaylor-NOAA/Lingcod_2021/settings/pages (maybe only Ian can do this) and enable bages
- [x] 2. Create docs folder and inside it, create
  - docs\North\
  - docs\South\
  - docs\index.html
- [x] 3. Add all the r4ss plots and html files to the folder for each model
- [x] 4. Make a copy of the `_SS_output.html` named `index.html` within each folder (leaving the original in places as well, as it represents the home tab and gets linked from the other tabs).
- [ ] 5. Use links in the document to reference these figures
- [x] 6. Add whatever other electronic appendix stuff we want

**Optional**:

- [ ] 7. Improve `docs\index.html`
- [ ] 8. Replace the index.html for each model with something more informative about what is shown

This will make referencing figures in the document much easier because they can each have a link.

**Comment by iantaylor-NOAA** [comment]
The r4ss html viewers for the latest north and south models are now available at https://iantaylor-noaa.github.io/Lingcod_2021/

The recent change in r4ss to put underscores at the front of the html files (e.g. `_SS_output_Bio.html`) works well for seeing those files at the top of a directory you open locally, but apparently causes problems for the Jekyll software that processes github pages. The work-around (discussed at https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/) is to add a `.nojekyll` file, which I did in d4fed00. That got the r4ss viewers working, but makes the index.md page no longer visible so I added an uglier index.html which got it working. We can refine this in the future but the links shouldn't change.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, here's some info on updating the lingcod files served on the web, where the example commands below are for the north. Obviously this could be cleaned up at the r4ss end but that's for another day.

1. put any extra plots you want into docs/North and docs/South and not within any sub-directories. Turns out r4ss::SS_html() uses `basename()` ([here](https://github.com/r4ss/r4ss/blob/main/R/SS_html.R#L109)), so additional folder structure isn't supported right now.
2. add a csv file with inputs like the following, with as many rows as you have figures.

file | caption | category | png_time | StartTime
-- | -- | -- | -- | --
VASTWestCoast_inputgrid.png | Test Caption. | VAST | 1 | StartTime: Sun Jun 27 16:53:34 2021

3. install the `pngtime` branch of r4ss or make [this trivial change](https://github.com/r4ss/r4ss/commit/e41135b0367bec2ca9ddf9812492bd27865920d2) locally.
4. load the output from the area in question into R via `mod.n <- get_mod("n", 22)` or `r4ss::SS_output()`
5. run `r4ss::SS_html(mod.n, plotdir = 'docs/North')`. It should automatically open a new `_SS_output.html` file that has a new VAST tab which in my case looks like this:
![image](https://user-images.githubusercontent.com/4992918/124220400-ac056280-dab2-11eb-83ba-0969758d63eb.png)
6. manually merge the existing `North/index.html` (which I edited by hand) and the new `North/_SS_output.html` (which you just created) so that both files are the same and contain the links to the new VAST tab in the upper part while retaining any of the hand-edited stuff at the bottom (e.g. disclaimer, link to South model, etc).
7. open index.html on your computer and make it and the rest of the tabs look right.
8. commit your changes to the repo
9. wait about 5 minutes for them to get processed by github
10. confirm that things look right at https://iantaylor-noaa.github.io/Lingcod_2021/North/.
11. if they do, repeat for the other area, adapting steps 4-6 as needed. If it looks wrong, revert the commit and try something different.

**Comment by kellijohnson-NOAA** [comment]
VAST plots were added finally with 8a7f434

**Comment by iantaylor-NOAA** [comment]
This issue seems adequately complete. There are additional ideas related to adding text about what is shown, but they can wait for another year, or at least after the review.
